# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "CGO_ENABLED=1 go build -ldflags='-s' -v -o tmp/leviosa ./cmd/leviosa"
bin = "tmp/leviosa"
full_bin = "./tmp/leviosa"
log = "debug"

[watcher]
extensions = ["go"]
dirs = ["cmd", "internal", "pkg", "migrations"]
