// Code generated by encx-gen. DO NOT EDIT.
// Source: allocation.go
// Generated: 2025-11-26T06:46:18+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// RoomAllocationEncx represents the encrypted version of RoomAllocation
type RoomAllocationEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	RoomID uuid.UUID `db:"roomid" json:"roomid"`
	
	AllocationType AllocationType `db:"allocationtype" json:"allocationtype"`
	
	StartDate *time.Time `db:"startdate" json:"startdate"`
	
	EndDate *time.Time `db:"enddate" json:"enddate"`
	
	IsActive bool `db:"isactive" json:"isactive"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	UserIDEncrypted []byte `db:"userid_encrypted" json:"userid_encrypted"`
	
	UserIDHash string `db:"userid_hash" json:"userid_hash"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessRoomAllocationEncx encrypts and hashes fields based on encx tags
func ProcessRoomAllocationEncx(ctx context.Context, crypto encx.CryptoService, source *RoomAllocation) (*RoomAllocationEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &RoomAllocationEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.RoomID = source.RoomID
	
	result.AllocationType = source.AllocationType
	
	result.StartDate = source.StartDate
	
	result.EndDate = source.EndDate
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process UserID (encrypt + hash_basic)
	if source.UserID != uuid.Nil {
	UserIDBytes, err := encx.SerializeValue(source.UserID)
	if err != nil {
		errs.Set("UserID serialization", err)
	} else {
		result.UserIDEncrypted, err = crypto.EncryptData(ctx, UserIDBytes, dek)
		if err != nil {
			errs.Set("UserID encryption", err)
		}
		result.UserIDHash = crypto.HashBasic(ctx, UserIDBytes)
		
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptRoomAllocationEncx decrypts the encrypted struct back to original
func DecryptRoomAllocationEncx(ctx context.Context, crypto encx.CryptoService, source *RoomAllocationEncx) (*RoomAllocation, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &RoomAllocation{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.RoomID = source.RoomID
	
	result.AllocationType = source.AllocationType
	
	result.StartDate = source.StartDate
	
	result.EndDate = source.EndDate
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt UserID
	if len(source.UserIDEncrypted) > 0 {
		UserIDBytes, err := crypto.DecryptData(ctx, source.UserIDEncrypted, dek)
		if err != nil {
			errs.Set("UserID decryption", err)
		} else {
			err = encx.DeserializeValue(UserIDBytes, &result.UserID)
			if err != nil {
				errs.Set("UserID deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
