// Code generated by encx-gen. DO NOT EDIT.
// Source: availability.go
// Generated: 2025-11-23T10:05:41+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// AvailabilityEncx represents the encrypted version of Availability
type AvailabilityEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	UserID uuid.UUID `db:"userid" json:"userid"`
	
	RoomID uuid.UUID `db:"roomid" json:"roomid"`
	
	StartTime time.Time `db:"starttime" json:"starttime"`
	
	EndTime time.Time `db:"endtime" json:"endtime"`
	
	PriceCents *int `db:"pricecents" json:"pricecents"`
	
	MaxCapacity int `db:"maxcapacity" json:"maxcapacity"`
	
	IsRecurring bool `db:"isrecurring" json:"isrecurring"`
	
	RecurrencePattern *RecurrencePattern `db:"recurrencepattern" json:"recurrencepattern"`
	
	Status AvailabilityStatus `db:"status" json:"status"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	ServiceTypeEncrypted []byte `db:"servicetype_encrypted" json:"servicetype_encrypted"`
	
	NotesEncrypted []byte `db:"notes_encrypted" json:"notes_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessAvailabilityEncx encrypts and hashes fields based on encx tags
func ProcessAvailabilityEncx(ctx context.Context, crypto encx.CryptoService, source *Availability) (*AvailabilityEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &AvailabilityEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.UserID = source.UserID
	
	result.RoomID = source.RoomID
	
	result.StartTime = source.StartTime
	
	result.EndTime = source.EndTime
	
	result.PriceCents = source.PriceCents
	
	result.MaxCapacity = source.MaxCapacity
	
	result.IsRecurring = source.IsRecurring
	
	result.RecurrencePattern = source.RecurrencePattern
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process ServiceType (encrypt)
	ServiceTypeBytes, err := encx.SerializeValue(source.ServiceType)
	if err != nil {
		errs.Set("ServiceType serialization", err)
	} else {
		result.ServiceTypeEncrypted, err = crypto.EncryptData(ctx, ServiceTypeBytes, dek)
		if err != nil {
			errs.Set("ServiceType encryption", err)
		}
	}
	
	
	
	// Process Notes (encrypt)
	NotesBytes, err := encx.SerializeValue(source.Notes)
	if err != nil {
		errs.Set("Notes serialization", err)
	} else {
		result.NotesEncrypted, err = crypto.EncryptData(ctx, NotesBytes, dek)
		if err != nil {
			errs.Set("Notes encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptAvailabilityEncx decrypts the encrypted struct back to original
func DecryptAvailabilityEncx(ctx context.Context, crypto encx.CryptoService, source *AvailabilityEncx) (*Availability, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Availability{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.UserID = source.UserID
	
	result.RoomID = source.RoomID
	
	result.StartTime = source.StartTime
	
	result.EndTime = source.EndTime
	
	result.PriceCents = source.PriceCents
	
	result.MaxCapacity = source.MaxCapacity
	
	result.IsRecurring = source.IsRecurring
	
	result.RecurrencePattern = source.RecurrencePattern
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt ServiceType
	if len(source.ServiceTypeEncrypted) > 0 {
		ServiceTypeBytes, err := crypto.DecryptData(ctx, source.ServiceTypeEncrypted, dek)
		if err != nil {
			errs.Set("ServiceType decryption", err)
		} else {
			err = encx.DeserializeValue(ServiceTypeBytes, &result.ServiceType)
			if err != nil {
				errs.Set("ServiceType deserialization", err)
			}
		}
	}
	
	
	// Decrypt Notes
	if len(source.NotesEncrypted) > 0 {
		NotesBytes, err := crypto.DecryptData(ctx, source.NotesEncrypted, dek)
		if err != nil {
			errs.Set("Notes decryption", err)
		} else {
			err = encx.DeserializeValue(NotesBytes, &result.Notes)
			if err != nil {
				errs.Set("Notes deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
