// Code generated by encx-gen. DO NOT EDIT.
// Source: booking.go
// Generated: 2025-11-23T22:37:13+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// BookingEncx represents the encrypted version of Booking
type BookingEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	AvailabilityID uuid.UUID `db:"availabilityid" json:"availabilityid"`
	
	ClientID uuid.UUID `db:"clientid" json:"clientid"`
	
	PartnerID uuid.UUID `db:"partnerid" json:"partnerid"`
	
	RoomID uuid.UUID `db:"roomid" json:"roomid"`
	
	TotalPriceCents int `db:"totalpricecents" json:"totalpricecents"`
	
	Currency string `db:"currency" json:"currency"`
	
	PaymentStatus PaymentStatus `db:"paymentstatus" json:"paymentstatus"`
	
	PaymentIntentID *string `db:"paymentintentid" json:"paymentintentid"`
	
	Status BookingStatus `db:"status" json:"status"`
	
	CancelledAt *time.Time `db:"cancelledat" json:"cancelledat"`
	
	CompletedAt *time.Time `db:"completedat" json:"completedat"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	ClientNotesEncrypted []byte `db:"clientnotes_encrypted" json:"clientnotes_encrypted"`
	
	PartnerNotesEncrypted []byte `db:"partnernotes_encrypted" json:"partnernotes_encrypted"`
	
	CancellationReasonEncrypted []byte `db:"cancellationreason_encrypted" json:"cancellationreason_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessBookingEncx encrypts and hashes fields based on encx tags
func ProcessBookingEncx(ctx context.Context, crypto encx.CryptoService, source *Booking) (*BookingEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &BookingEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.AvailabilityID = source.AvailabilityID
	
	result.ClientID = source.ClientID
	
	result.PartnerID = source.PartnerID
	
	result.RoomID = source.RoomID
	
	result.TotalPriceCents = source.TotalPriceCents
	
	result.Currency = source.Currency
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaymentIntentID = source.PaymentIntentID
	
	result.Status = source.Status
	
	result.CancelledAt = source.CancelledAt
	
	result.CompletedAt = source.CompletedAt
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process ClientNotes (encrypt)
	ClientNotesBytes, err := encx.SerializeValue(source.ClientNotes)
	if err != nil {
		errs.Set("ClientNotes serialization", err)
	} else {
		result.ClientNotesEncrypted, err = crypto.EncryptData(ctx, ClientNotesBytes, dek)
		if err != nil {
			errs.Set("ClientNotes encryption", err)
		}
	}
	
	
	
	// Process PartnerNotes (encrypt)
	PartnerNotesBytes, err := encx.SerializeValue(source.PartnerNotes)
	if err != nil {
		errs.Set("PartnerNotes serialization", err)
	} else {
		result.PartnerNotesEncrypted, err = crypto.EncryptData(ctx, PartnerNotesBytes, dek)
		if err != nil {
			errs.Set("PartnerNotes encryption", err)
		}
	}
	
	
	
	// Process CancellationReason (encrypt)
	CancellationReasonBytes, err := encx.SerializeValue(source.CancellationReason)
	if err != nil {
		errs.Set("CancellationReason serialization", err)
	} else {
		result.CancellationReasonEncrypted, err = crypto.EncryptData(ctx, CancellationReasonBytes, dek)
		if err != nil {
			errs.Set("CancellationReason encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptBookingEncx decrypts the encrypted struct back to original
func DecryptBookingEncx(ctx context.Context, crypto encx.CryptoService, source *BookingEncx) (*Booking, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Booking{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.AvailabilityID = source.AvailabilityID
	
	result.ClientID = source.ClientID
	
	result.PartnerID = source.PartnerID
	
	result.RoomID = source.RoomID
	
	result.TotalPriceCents = source.TotalPriceCents
	
	result.Currency = source.Currency
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaymentIntentID = source.PaymentIntentID
	
	result.Status = source.Status
	
	result.CancelledAt = source.CancelledAt
	
	result.CompletedAt = source.CompletedAt
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt ClientNotes
	if len(source.ClientNotesEncrypted) > 0 {
		ClientNotesBytes, err := crypto.DecryptData(ctx, source.ClientNotesEncrypted, dek)
		if err != nil {
			errs.Set("ClientNotes decryption", err)
		} else {
			err = encx.DeserializeValue(ClientNotesBytes, &result.ClientNotes)
			if err != nil {
				errs.Set("ClientNotes deserialization", err)
			}
		}
	}
	
	
	// Decrypt PartnerNotes
	if len(source.PartnerNotesEncrypted) > 0 {
		PartnerNotesBytes, err := crypto.DecryptData(ctx, source.PartnerNotesEncrypted, dek)
		if err != nil {
			errs.Set("PartnerNotes decryption", err)
		} else {
			err = encx.DeserializeValue(PartnerNotesBytes, &result.PartnerNotes)
			if err != nil {
				errs.Set("PartnerNotes deserialization", err)
			}
		}
	}
	
	
	// Decrypt CancellationReason
	if len(source.CancellationReasonEncrypted) > 0 {
		CancellationReasonBytes, err := crypto.DecryptData(ctx, source.CancellationReasonEncrypted, dek)
		if err != nil {
			errs.Set("CancellationReason decryption", err)
		} else {
			err = encx.DeserializeValue(CancellationReasonBytes, &result.CancellationReason)
			if err != nil {
				errs.Set("CancellationReason deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
