// Code generated by encx-gen. DO NOT EDIT.
// Source: booking.go
// Generated: 2026-04-27T17:51:29+02:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// BookingEncx represents the encrypted version of Booking
type BookingEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	AvailabilityID uuid.UUID `db:"availabilityid" json:"availabilityid"`
	
	ClientID *uuid.UUID `db:"clientid" json:"clientid"`
	
	PartnerID uuid.UUID `db:"partnerid" json:"partnerid"`
	
	RoomID uuid.UUID `db:"roomid" json:"roomid"`
	
	TotalPriceCents int `db:"totalpricecents" json:"totalpricecents"`
	
	Currency string `db:"currency" json:"currency"`
	
	PaymentStatus PaymentStatus `db:"paymentstatus" json:"paymentstatus"`
	
	PaymentIntentID *string `db:"paymentintentid" json:"paymentintentid"`
	
	Status BookingStatus `db:"status" json:"status"`
	
	CancelledAt *time.Time `db:"cancelledat" json:"cancelledat"`
	
	CompletedAt *time.Time `db:"completedat" json:"completedat"`
	
	Token string `db:"token" json:"token"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	ProductIDEncrypted []byte `db:"productid_encrypted" json:"productid_encrypted"`
	
	SlotStartTimeEncrypted []byte `db:"slotstarttime_encrypted" json:"slotstarttime_encrypted"`
	
	SlotEndTimeEncrypted []byte `db:"slotendtime_encrypted" json:"slotendtime_encrypted"`
	
	ClientNotesEncrypted []byte `db:"clientnotes_encrypted" json:"clientnotes_encrypted"`
	
	PartnerNotesEncrypted []byte `db:"partnernotes_encrypted" json:"partnernotes_encrypted"`
	
	CancellationReasonEncrypted []byte `db:"cancellationreason_encrypted" json:"cancellationreason_encrypted"`
	
	GuestFirstNameEncrypted []byte `db:"guestfirstname_encrypted" json:"guestfirstname_encrypted"`
	
	GuestLastNameEncrypted []byte `db:"guestlastname_encrypted" json:"guestlastname_encrypted"`
	
	GuestEmailEncrypted []byte `db:"guestemail_encrypted" json:"guestemail_encrypted"`
	
	GuestPhoneEncrypted []byte `db:"guestphone_encrypted" json:"guestphone_encrypted"`

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessBookingEncx encrypts and hashes fields based on encx tags
func ProcessBookingEncx(ctx context.Context, crypto encx.CryptoService, source *Booking) (*BookingEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &BookingEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.AvailabilityID = source.AvailabilityID
	
	result.ClientID = source.ClientID
	
	result.PartnerID = source.PartnerID
	
	result.RoomID = source.RoomID
	
	result.TotalPriceCents = source.TotalPriceCents
	
	result.Currency = source.Currency
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaymentIntentID = source.PaymentIntentID
	
	result.Status = source.Status
	
	result.Token = source.Token
	
	result.CancelledAt = source.CancelledAt
	
	result.CompletedAt = source.CompletedAt
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process ProductID (encrypt)
	if source.ProductID != uuid.Nil {
	ProductIDBytes, err := encx.SerializeValue(source.ProductID)
	if err != nil {
		errs.Set("ProductID serialization", err)
	} else {
		result.ProductIDEncrypted, err = crypto.EncryptData(ctx, ProductIDBytes, dek)
		if err != nil {
			errs.Set("ProductID encryption", err)
		}
	}
	}
	
	
	
	// Process SlotStartTime (encrypt)
	if !source.SlotStartTime.IsZero() {
	SlotStartTimeBytes, err := encx.SerializeValue(source.SlotStartTime)
	if err != nil {
		errs.Set("SlotStartTime serialization", err)
	} else {
		result.SlotStartTimeEncrypted, err = crypto.EncryptData(ctx, SlotStartTimeBytes, dek)
		if err != nil {
			errs.Set("SlotStartTime encryption", err)
		}
	}
	}
	
	
	
	// Process SlotEndTime (encrypt)
	if !source.SlotEndTime.IsZero() {
	SlotEndTimeBytes, err := encx.SerializeValue(source.SlotEndTime)
	if err != nil {
		errs.Set("SlotEndTime serialization", err)
	} else {
		result.SlotEndTimeEncrypted, err = crypto.EncryptData(ctx, SlotEndTimeBytes, dek)
		if err != nil {
			errs.Set("SlotEndTime encryption", err)
		}
	}
	}
	
	
	
	// Process ClientNotes (encrypt)
	ClientNotesBytes, err := encx.SerializeValue(source.ClientNotes)
	if err != nil {
		errs.Set("ClientNotes serialization", err)
	} else {
		result.ClientNotesEncrypted, err = crypto.EncryptData(ctx, ClientNotesBytes, dek)
		if err != nil {
			errs.Set("ClientNotes encryption", err)
		}
	}
	
	
	
	// Process PartnerNotes (encrypt)
	PartnerNotesBytes, err := encx.SerializeValue(source.PartnerNotes)
	if err != nil {
		errs.Set("PartnerNotes serialization", err)
	} else {
		result.PartnerNotesEncrypted, err = crypto.EncryptData(ctx, PartnerNotesBytes, dek)
		if err != nil {
			errs.Set("PartnerNotes encryption", err)
		}
	}
	
	
	
	// Process CancellationReason (encrypt)
	CancellationReasonBytes, err := encx.SerializeValue(source.CancellationReason)
	if err != nil {
		errs.Set("CancellationReason serialization", err)
	} else {
		result.CancellationReasonEncrypted, err = crypto.EncryptData(ctx, CancellationReasonBytes, dek)
		if err != nil {
			errs.Set("CancellationReason encryption", err)
		}
	}
	
	
	
	// Process GuestFirstName (encrypt)
	if source.GuestFirstName != "" {
	GuestFirstNameBytes, err := encx.SerializeValue(source.GuestFirstName)
	if err != nil {
		errs.Set("GuestFirstName serialization", err)
	} else {
		result.GuestFirstNameEncrypted, err = crypto.EncryptData(ctx, GuestFirstNameBytes, dek)
		if err != nil {
			errs.Set("GuestFirstName encryption", err)
		}
	}
	}



	// Process GuestLastName (encrypt)
	if source.GuestLastName != "" {
	GuestLastNameBytes, err := encx.SerializeValue(source.GuestLastName)
	if err != nil {
		errs.Set("GuestLastName serialization", err)
	} else {
		result.GuestLastNameEncrypted, err = crypto.EncryptData(ctx, GuestLastNameBytes, dek)
		if err != nil {
			errs.Set("GuestLastName encryption", err)
		}
	}
	}



	// Process GuestEmail (encrypt)
	if source.GuestEmail != "" {
	GuestEmailBytes, err := encx.SerializeValue(source.GuestEmail)
	if err != nil {
		errs.Set("GuestEmail serialization", err)
	} else {
		result.GuestEmailEncrypted, err = crypto.EncryptData(ctx, GuestEmailBytes, dek)
		if err != nil {
			errs.Set("GuestEmail encryption", err)
		}
	}
	}



	// Process GuestPhone (encrypt)
	if source.GuestPhone != "" {
	GuestPhoneBytes, err := encx.SerializeValue(source.GuestPhone)
	if err != nil {
		errs.Set("GuestPhone serialization", err)
	} else {
		result.GuestPhoneEncrypted, err = crypto.EncryptData(ctx, GuestPhoneBytes, dek)
		if err != nil {
			errs.Set("GuestPhone encryption", err)
		}
	}
	}
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptBookingEncx decrypts the encrypted struct back to original
func DecryptBookingEncx(ctx context.Context, crypto encx.CryptoService, source *BookingEncx) (*Booking, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Booking{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.AvailabilityID = source.AvailabilityID
	
	result.ClientID = source.ClientID
	
	result.PartnerID = source.PartnerID
	
	result.RoomID = source.RoomID
	
	result.TotalPriceCents = source.TotalPriceCents
	
	result.Currency = source.Currency
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaymentIntentID = source.PaymentIntentID
	
	result.Status = source.Status
	
	result.Token = source.Token
	
	result.CancelledAt = source.CancelledAt
	
	result.CompletedAt = source.CompletedAt
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt ProductID
	if len(source.ProductIDEncrypted) > 0 {
		ProductIDBytes, err := crypto.DecryptData(ctx, source.ProductIDEncrypted, dek)
		if err != nil {
			errs.Set("ProductID decryption", err)
		} else {
			err = encx.DeserializeValue(ProductIDBytes, &result.ProductID)
			if err != nil {
				errs.Set("ProductID deserialization", err)
			}
		}
	}
	
	
	// Decrypt SlotStartTime
	if len(source.SlotStartTimeEncrypted) > 0 {
		SlotStartTimeBytes, err := crypto.DecryptData(ctx, source.SlotStartTimeEncrypted, dek)
		if err != nil {
			errs.Set("SlotStartTime decryption", err)
		} else {
			err = encx.DeserializeValue(SlotStartTimeBytes, &result.SlotStartTime)
			if err != nil {
				errs.Set("SlotStartTime deserialization", err)
			}
		}
	}
	
	
	// Decrypt SlotEndTime
	if len(source.SlotEndTimeEncrypted) > 0 {
		SlotEndTimeBytes, err := crypto.DecryptData(ctx, source.SlotEndTimeEncrypted, dek)
		if err != nil {
			errs.Set("SlotEndTime decryption", err)
		} else {
			err = encx.DeserializeValue(SlotEndTimeBytes, &result.SlotEndTime)
			if err != nil {
				errs.Set("SlotEndTime deserialization", err)
			}
		}
	}
	
	
	// Decrypt ClientNotes
	if len(source.ClientNotesEncrypted) > 0 {
		ClientNotesBytes, err := crypto.DecryptData(ctx, source.ClientNotesEncrypted, dek)
		if err != nil {
			errs.Set("ClientNotes decryption", err)
		} else {
			err = encx.DeserializeValue(ClientNotesBytes, &result.ClientNotes)
			if err != nil {
				errs.Set("ClientNotes deserialization", err)
			}
		}
	}
	
	
	// Decrypt PartnerNotes
	if len(source.PartnerNotesEncrypted) > 0 {
		PartnerNotesBytes, err := crypto.DecryptData(ctx, source.PartnerNotesEncrypted, dek)
		if err != nil {
			errs.Set("PartnerNotes decryption", err)
		} else {
			err = encx.DeserializeValue(PartnerNotesBytes, &result.PartnerNotes)
			if err != nil {
				errs.Set("PartnerNotes deserialization", err)
			}
		}
	}
	
	
	// Decrypt CancellationReason
	if len(source.CancellationReasonEncrypted) > 0 {
		CancellationReasonBytes, err := crypto.DecryptData(ctx, source.CancellationReasonEncrypted, dek)
		if err != nil {
			errs.Set("CancellationReason decryption", err)
		} else {
			err = encx.DeserializeValue(CancellationReasonBytes, &result.CancellationReason)
			if err != nil {
				errs.Set("CancellationReason deserialization", err)
			}
		}
	}
	
	
	// Decrypt GuestFirstName
	if len(source.GuestFirstNameEncrypted) > 0 {
		GuestFirstNameBytes, err := crypto.DecryptData(ctx, source.GuestFirstNameEncrypted, dek)
		if err != nil {
			errs.Set("GuestFirstName decryption", err)
		} else {
			err = encx.DeserializeValue(GuestFirstNameBytes, &result.GuestFirstName)
			if err != nil {
				errs.Set("GuestFirstName deserialization", err)
			}
		}
	}
	
	
	// Decrypt GuestLastName
	if len(source.GuestLastNameEncrypted) > 0 {
		GuestLastNameBytes, err := crypto.DecryptData(ctx, source.GuestLastNameEncrypted, dek)
		if err != nil {
			errs.Set("GuestLastName decryption", err)
		} else {
			err = encx.DeserializeValue(GuestLastNameBytes, &result.GuestLastName)
			if err != nil {
				errs.Set("GuestLastName deserialization", err)
			}
		}
	}
	
	
	// Decrypt GuestEmail
	if len(source.GuestEmailEncrypted) > 0 {
		GuestEmailBytes, err := crypto.DecryptData(ctx, source.GuestEmailEncrypted, dek)
		if err != nil {
			errs.Set("GuestEmail decryption", err)
		} else {
			err = encx.DeserializeValue(GuestEmailBytes, &result.GuestEmail)
			if err != nil {
				errs.Set("GuestEmail deserialization", err)
			}
		}
	}
	
	
	// Decrypt GuestPhone
	if len(source.GuestPhoneEncrypted) > 0 {
		GuestPhoneBytes, err := crypto.DecryptData(ctx, source.GuestPhoneEncrypted, dek)
		if err != nil {
			errs.Set("GuestPhone decryption", err)
		} else {
			err = encx.DeserializeValue(GuestPhoneBytes, &result.GuestPhone)
			if err != nil {
				errs.Set("GuestPhone deserialization", err)
			}
		}
	}

	return result, errs.AsError()
}
