// Code generated by encx-gen. DO NOT EDIT.
// Source: room.go
// Generated: 2025-11-23T23:01:51+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// RoomEncx represents the encrypted version of Room
type RoomEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	BuildingID uuid.UUID `db:"buildingid" json:"buildingid"`
	
	Capacity int `db:"capacity" json:"capacity"`
	
	OperatingStartTime time.Time `db:"operatingstarttime" json:"operatingstarttime"`
	
	OperatingEndTime time.Time `db:"operatingendtime" json:"operatingendtime"`
	
	IsActive bool `db:"isactive" json:"isactive"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	NameEncrypted []byte `db:"name_encrypted" json:"name_encrypted"`
	
	NameHash string `db:"name_hash" json:"name_hash"`
	
	DescriptionEncrypted []byte `db:"description_encrypted" json:"description_encrypted"`
	
	RoomNumberEncrypted []byte `db:"roomnumber_encrypted" json:"roomnumber_encrypted"`
	
	RoomNumberHash string `db:"roomnumber_hash" json:"roomnumber_hash"`
	
	EquipmentEncrypted []byte `db:"equipment_encrypted" json:"equipment_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessRoomEncx encrypts and hashes fields based on encx tags
func ProcessRoomEncx(ctx context.Context, crypto encx.CryptoService, source *Room) (*RoomEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &RoomEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.BuildingID = source.BuildingID
	
	result.Capacity = source.Capacity
	
	result.OperatingStartTime = source.OperatingStartTime
	
	result.OperatingEndTime = source.OperatingEndTime
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Name (encrypt + hash_basic)
	NameBytes, err := encx.SerializeValue(source.Name)
	if err != nil {
		errs.Set("Name serialization", err)
	} else {
		result.NameEncrypted, err = crypto.EncryptData(ctx, NameBytes, dek)
		if err != nil {
			errs.Set("Name encryption", err)
		}
		result.NameHash = crypto.HashBasic(ctx, NameBytes)
		
	}
	
	
	
	// Process Description (encrypt)
	DescriptionBytes, err := encx.SerializeValue(source.Description)
	if err != nil {
		errs.Set("Description serialization", err)
	} else {
		result.DescriptionEncrypted, err = crypto.EncryptData(ctx, DescriptionBytes, dek)
		if err != nil {
			errs.Set("Description encryption", err)
		}
	}
	
	
	
	// Process RoomNumber (encrypt + hash_basic)
	RoomNumberBytes, err := encx.SerializeValue(source.RoomNumber)
	if err != nil {
		errs.Set("RoomNumber serialization", err)
	} else {
		result.RoomNumberEncrypted, err = crypto.EncryptData(ctx, RoomNumberBytes, dek)
		if err != nil {
			errs.Set("RoomNumber encryption", err)
		}
		result.RoomNumberHash = crypto.HashBasic(ctx, RoomNumberBytes)
		
	}
	
	
	
	// Process Equipment (encrypt)
	EquipmentBytes, err := encx.SerializeValue(source.Equipment)
	if err != nil {
		errs.Set("Equipment serialization", err)
	} else {
		result.EquipmentEncrypted, err = crypto.EncryptData(ctx, EquipmentBytes, dek)
		if err != nil {
			errs.Set("Equipment encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptRoomEncx decrypts the encrypted struct back to original
func DecryptRoomEncx(ctx context.Context, crypto encx.CryptoService, source *RoomEncx) (*Room, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Room{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.BuildingID = source.BuildingID
	
	result.Capacity = source.Capacity
	
	result.OperatingStartTime = source.OperatingStartTime
	
	result.OperatingEndTime = source.OperatingEndTime
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Name
	if len(source.NameEncrypted) > 0 {
		NameBytes, err := crypto.DecryptData(ctx, source.NameEncrypted, dek)
		if err != nil {
			errs.Set("Name decryption", err)
		} else {
			err = encx.DeserializeValue(NameBytes, &result.Name)
			if err != nil {
				errs.Set("Name deserialization", err)
			}
		}
	}
	
	
	// Decrypt Description
	if len(source.DescriptionEncrypted) > 0 {
		DescriptionBytes, err := crypto.DecryptData(ctx, source.DescriptionEncrypted, dek)
		if err != nil {
			errs.Set("Description decryption", err)
		} else {
			err = encx.DeserializeValue(DescriptionBytes, &result.Description)
			if err != nil {
				errs.Set("Description deserialization", err)
			}
		}
	}
	
	
	// Decrypt RoomNumber
	if len(source.RoomNumberEncrypted) > 0 {
		RoomNumberBytes, err := crypto.DecryptData(ctx, source.RoomNumberEncrypted, dek)
		if err != nil {
			errs.Set("RoomNumber decryption", err)
		} else {
			err = encx.DeserializeValue(RoomNumberBytes, &result.RoomNumber)
			if err != nil {
				errs.Set("RoomNumber deserialization", err)
			}
		}
	}
	
	
	// Decrypt Equipment
	if len(source.EquipmentEncrypted) > 0 {
		EquipmentBytes, err := crypto.DecryptData(ctx, source.EquipmentEncrypted, dek)
		if err != nil {
			errs.Set("Equipment decryption", err)
		} else {
			err = encx.DeserializeValue(EquipmentBytes, &result.Equipment)
			if err != nil {
				errs.Set("Equipment deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
