// Code generated by encx-gen. DO NOT EDIT.
// Source: room_dto.go
// Generated: 2025-11-23T23:01:51+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// CreateRoomRequestEncx represents the encrypted version of CreateRoomRequest
type CreateRoomRequestEncx struct {
	
	BuildingID uuid.UUID `db:"buildingid" json:"buildingid"`
	
	Name string `db:"name" json:"name"`
	
	Description string `db:"description" json:"description"`
	
	Capacity int `db:"capacity" json:"capacity"`
	
	Equipment []string `db:"equipment" json:"equipment"`
	
	OperatingStartTime *time.Time `db:"operatingstarttime" json:"operatingstarttime"`
	
	OperatingEndTime *time.Time `db:"operatingendtime" json:"operatingendtime"`
	
	IsActive bool `db:"isactive" json:"isactive"`
	
	
	RoomNumberEncrypted []byte `db:"roomnumber_encrypted" json:"roomnumber_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessCreateRoomRequestEncx encrypts and hashes fields based on encx tags
func ProcessCreateRoomRequestEncx(ctx context.Context, crypto encx.CryptoService, source *CreateRoomRequest) (*CreateRoomRequestEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &CreateRoomRequestEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.BuildingID = source.BuildingID
	
	result.Name = source.Name
	
	result.Description = source.Description
	
	result.Capacity = source.Capacity
	
	result.Equipment = source.Equipment
	
	result.OperatingStartTime = source.OperatingStartTime
	
	result.OperatingEndTime = source.OperatingEndTime
	
	result.IsActive = source.IsActive
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process RoomNumber (encrypt)
	RoomNumberBytes, err := encx.SerializeValue(source.RoomNumber)
	if err != nil {
		errs.Set("RoomNumber serialization", err)
	} else {
		result.RoomNumberEncrypted, err = crypto.EncryptData(ctx, RoomNumberBytes, dek)
		if err != nil {
			errs.Set("RoomNumber encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptCreateRoomRequestEncx decrypts the encrypted struct back to original
func DecryptCreateRoomRequestEncx(ctx context.Context, crypto encx.CryptoService, source *CreateRoomRequestEncx) (*CreateRoomRequest, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &CreateRoomRequest{}

	// Copy plain fields (non-encx fields)
	
	result.BuildingID = source.BuildingID
	
	result.Name = source.Name
	
	result.Description = source.Description
	
	result.Capacity = source.Capacity
	
	result.Equipment = source.Equipment
	
	result.OperatingStartTime = source.OperatingStartTime
	
	result.OperatingEndTime = source.OperatingEndTime
	
	result.IsActive = source.IsActive
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt RoomNumber
	if len(source.RoomNumberEncrypted) > 0 {
		RoomNumberBytes, err := crypto.DecryptData(ctx, source.RoomNumberEncrypted, dek)
		if err != nil {
			errs.Set("RoomNumber decryption", err)
		} else {
			err = encx.DeserializeValue(RoomNumberBytes, &result.RoomNumber)
			if err != nil {
				errs.Set("RoomNumber deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
