auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki
  storage:
    s3:
      bucketnames: staging-leviosa-loki-logs
      endpoint: s3.amazonaws.com
      region: eu-central-1
      s3forcepathstyle: false  # Optional, useful for MinIO
      insecure: false          # Optional, useful for local S3
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
