---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH
  ansible.builtin.ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP
  ansible.builtin.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  ansible.builtin.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Deny all other incoming traffic
  ansible.builtin.ufw:
    rule: deny
    direction: in

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled

- name: Ensure UFW is running
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes
