// Code generated by encx-gen. DO NOT EDIT.
// Source: building.go
// Generated: 2025-10-09T09:35:59+02:00

package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"

)

// BuildingEncx represents the encrypted version of Building
type BuildingEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	IsActive bool `db:"isactive" json:"isactive"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	NameEncrypted []byte `db:"name_encrypted" json:"name_encrypted"`
	
	AddressEncrypted []byte `db:"address_encrypted" json:"address_encrypted"`
	
	CityEncrypted []byte `db:"city_encrypted" json:"city_encrypted"`
	
	PostalCodeEncrypted []byte `db:"postalcode_encrypted" json:"postalcode_encrypted"`
	
	CountryEncrypted []byte `db:"country_encrypted" json:"country_encrypted"`
	
	DescriptionEncrypted []byte `db:"description_encrypted" json:"description_encrypted"`
	
	PhoneEncrypted []byte `db:"phone_encrypted" json:"phone_encrypted"`
	
	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessBuildingEncx encrypts and hashes fields based on encx tags
func ProcessBuildingEncx(ctx context.Context, crypto encx.CryptoService, source *Building) (*BuildingEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &BuildingEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Name (encrypt)
	if source.Name != "" {
		NameBytes, err := encx.SerializeValue(source.Name)
		if err != nil {
			errs.Set("Name serialization", err)
		} else {
			result.NameEncrypted, err = crypto.EncryptData(ctx, NameBytes, dek)
			if err != nil {
				errs.Set("Name encryption", err)
			}
		}
	}
	
	
	// Process Address (encrypt)
	if source.Address != "" {
		AddressBytes, err := encx.SerializeValue(source.Address)
		if err != nil {
			errs.Set("Address serialization", err)
		} else {
			result.AddressEncrypted, err = crypto.EncryptData(ctx, AddressBytes, dek)
			if err != nil {
				errs.Set("Address encryption", err)
			}
		}
	}
	
	
	// Process City (encrypt)
	if source.City != "" {
		CityBytes, err := encx.SerializeValue(source.City)
		if err != nil {
			errs.Set("City serialization", err)
		} else {
			result.CityEncrypted, err = crypto.EncryptData(ctx, CityBytes, dek)
			if err != nil {
				errs.Set("City encryption", err)
			}
		}
	}
	
	
	// Process PostalCode (encrypt)
	if source.PostalCode != "" {
		PostalCodeBytes, err := encx.SerializeValue(source.PostalCode)
		if err != nil {
			errs.Set("PostalCode serialization", err)
		} else {
			result.PostalCodeEncrypted, err = crypto.EncryptData(ctx, PostalCodeBytes, dek)
			if err != nil {
				errs.Set("PostalCode encryption", err)
			}
		}
	}
	
	
	// Process Country (encrypt)
	if source.Country != "" {
		CountryBytes, err := encx.SerializeValue(source.Country)
		if err != nil {
			errs.Set("Country serialization", err)
		} else {
			result.CountryEncrypted, err = crypto.EncryptData(ctx, CountryBytes, dek)
			if err != nil {
				errs.Set("Country encryption", err)
			}
		}
	}
	
	
	// Process Description (encrypt)
	if source.Description != "" {
		DescriptionBytes, err := encx.SerializeValue(source.Description)
		if err != nil {
			errs.Set("Description serialization", err)
		} else {
			result.DescriptionEncrypted, err = crypto.EncryptData(ctx, DescriptionBytes, dek)
			if err != nil {
				errs.Set("Description encryption", err)
			}
		}
	}
	
	
	// Process Phone (encrypt)
	if source.Phone != "" {
		PhoneBytes, err := encx.SerializeValue(source.Phone)
		if err != nil {
			errs.Set("Phone serialization", err)
		} else {
			result.PhoneEncrypted, err = crypto.EncryptData(ctx, PhoneBytes, dek)
			if err != nil {
				errs.Set("Phone encryption", err)
			}
		}
	}
	
	
	// Process Email (encrypt)
	if source.Email != "" {
		EmailBytes, err := encx.SerializeValue(source.Email)
		if err != nil {
			errs.Set("Email serialization", err)
		} else {
			result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
			if err != nil {
				errs.Set("Email encryption", err)
			}
		}
	}
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptBuildingEncx decrypts the encrypted struct back to original
func DecryptBuildingEncx(ctx context.Context, crypto encx.CryptoService, source *BuildingEncx) (*Building, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Building{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Name
	if len(source.NameEncrypted) > 0 {
		NameBytes, err := crypto.DecryptData(ctx, source.NameEncrypted, dek)
		if err != nil {
			errs.Set("Name decryption", err)
		} else {
			err = encx.DeserializeValue(NameBytes, &result.Name)
			if err != nil {
				errs.Set("Name deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address
	if len(source.AddressEncrypted) > 0 {
		AddressBytes, err := crypto.DecryptData(ctx, source.AddressEncrypted, dek)
		if err != nil {
			errs.Set("Address decryption", err)
		} else {
			err = encx.DeserializeValue(AddressBytes, &result.Address)
			if err != nil {
				errs.Set("Address deserialization", err)
			}
		}
	}
	
	
	// Decrypt City
	if len(source.CityEncrypted) > 0 {
		CityBytes, err := crypto.DecryptData(ctx, source.CityEncrypted, dek)
		if err != nil {
			errs.Set("City decryption", err)
		} else {
			err = encx.DeserializeValue(CityBytes, &result.City)
			if err != nil {
				errs.Set("City deserialization", err)
			}
		}
	}
	
	
	// Decrypt PostalCode
	if len(source.PostalCodeEncrypted) > 0 {
		PostalCodeBytes, err := crypto.DecryptData(ctx, source.PostalCodeEncrypted, dek)
		if err != nil {
			errs.Set("PostalCode decryption", err)
		} else {
			err = encx.DeserializeValue(PostalCodeBytes, &result.PostalCode)
			if err != nil {
				errs.Set("PostalCode deserialization", err)
			}
		}
	}
	
	
	// Decrypt Country
	if len(source.CountryEncrypted) > 0 {
		CountryBytes, err := crypto.DecryptData(ctx, source.CountryEncrypted, dek)
		if err != nil {
			errs.Set("Country decryption", err)
		} else {
			err = encx.DeserializeValue(CountryBytes, &result.Country)
			if err != nil {
				errs.Set("Country deserialization", err)
			}
		}
	}
	
	
	// Decrypt Description
	if len(source.DescriptionEncrypted) > 0 {
		DescriptionBytes, err := crypto.DecryptData(ctx, source.DescriptionEncrypted, dek)
		if err != nil {
			errs.Set("Description decryption", err)
		} else {
			err = encx.DeserializeValue(DescriptionBytes, &result.Description)
			if err != nil {
				errs.Set("Description deserialization", err)
			}
		}
	}
	
	
	// Decrypt Phone
	if len(source.PhoneEncrypted) > 0 {
		PhoneBytes, err := crypto.DecryptData(ctx, source.PhoneEncrypted, dek)
		if err != nil {
			errs.Set("Phone decryption", err)
		} else {
			err = encx.DeserializeValue(PhoneBytes, &result.Phone)
			if err != nil {
				errs.Set("Phone deserialization", err)
			}
		}
	}
	
	
	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
