---
- name: Install rclone
  ansible.builtin.apt:
    name: rclone
    state: present
    update_cache: yes

- name: Ensure rclone configuration directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/rclone
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Deploy rclone configuration file for AWS S3
  ansible.builtin.copy:
    content: |
      [{{ rclone_aws_remote_name }}]
      type = s3
      provider = AWS
      access_key_id = {{ rclone_aws_access_key }}
      secret_access_key = {{ rclone_aws_secret_key }}
      region = {{ rclone_aws_region }}
      endpoint = {{ rclone_aws_endpoint }}
      location_constraint = {{ rclone_aws_location_constraint }}
      acl = private
      storage_class = {{ rclone_aws_storage_class }}
    dest: /home/{{ user }}/.config/rclone/rclone.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'

- name: Ensure rclone is in the user's PATH
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    line: 'export PATH=$PATH:/usr/bin/rclone'
    create: yes

- name: Deploy the sync script from the files folder
  ansible.builtin.template:
    src: files/backup_database.sh.j2
    dest: /home/{{ user }}/scripts/backup_database.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Set up a cron job to run the sync script with sudo
  ansible.builtin.cron:
    name: "rclone sync script to backup application database"
    user: root
    job: "sudo -u /home/{{ user }}/scripts/backup_database.sh"
    minute: "0"
    hour: "*/6"
    state: present
