// Code generated by encx-gen. DO NOT EDIT.
// Source: settings.go
// Generated: 2026-04-27T17:51:29+02:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
)

// SettingEncryptedEncx represents the encrypted version of SettingEncrypted
type SettingEncryptedEncx struct {
	
	ID string `db:"id" json:"id"`
	
	Key string `db:"key" json:"key"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	ValueEncrypted []byte `db:"value_encrypted" json:"value_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessSettingEncryptedEncx encrypts and hashes fields based on encx tags
func ProcessSettingEncryptedEncx(ctx context.Context, crypto encx.CryptoService, source *SettingEncrypted) (*SettingEncryptedEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SettingEncryptedEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Key = source.Key
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Value (encrypt)
	ValueBytes, err := encx.SerializeValue(source.Value)
	if err != nil {
		errs.Set("Value serialization", err)
	} else {
		result.ValueEncrypted, err = crypto.EncryptData(ctx, ValueBytes, dek)
		if err != nil {
			errs.Set("Value encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptSettingEncryptedEncx decrypts the encrypted struct back to original
func DecryptSettingEncryptedEncx(ctx context.Context, crypto encx.CryptoService, source *SettingEncryptedEncx) (*SettingEncrypted, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SettingEncrypted{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Key = source.Key
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Value
	if len(source.ValueEncrypted) > 0 {
		ValueBytes, err := crypto.DecryptData(ctx, source.ValueEncrypted, dek)
		if err != nil {
			errs.Set("Value decryption", err)
		} else {
			err = encx.DeserializeValue(ValueBytes, &result.Value)
			if err != nil {
				errs.Set("Value deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
