// Code generated by encx-gen. DO NOT EDIT.
// Source: otp.go
// Generated: 2025-11-13T10:32:03+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
)

// OTPEncx represents the encrypted version of OTP
type OTPEncx struct {
	
	Attempts int `db:"attempts" json:"attempts"`
	
	ExpiresAt time.Time `db:"expiresat" json:"expiresat"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	EmailHash string `db:"email_hash" json:"email_hash"`
	
	CodeEncrypted []byte `db:"code_encrypted" json:"code_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessOTPEncx encrypts and hashes fields based on encx tags
func ProcessOTPEncx(ctx context.Context, crypto encx.CryptoService, source *OTP) (*OTPEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &OTPEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.Attempts = source.Attempts
	
	result.ExpiresAt = source.ExpiresAt
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Email (hash_basic)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)
	}
	
	
	
	// Process Code (encrypt)
	CodeBytes, err := encx.SerializeValue(source.Code)
	if err != nil {
		errs.Set("Code serialization", err)
	} else {
		result.CodeEncrypted, err = crypto.EncryptData(ctx, CodeBytes, dek)
		if err != nil {
			errs.Set("Code encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptOTPEncx decrypts the encrypted struct back to original
func DecryptOTPEncx(ctx context.Context, crypto encx.CryptoService, source *OTPEncx) (*OTP, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &OTP{}

	// Copy plain fields (non-encx fields)
	
	result.Attempts = source.Attempts
	
	result.ExpiresAt = source.ExpiresAt
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Code
	if len(source.CodeEncrypted) > 0 {
		CodeBytes, err := crypto.DecryptData(ctx, source.CodeEncrypted, dek)
		if err != nil {
			errs.Set("Code decryption", err)
		} else {
			err = encx.DeserializeValue(CodeBytes, &result.Code)
			if err != nil {
				errs.Set("Code deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
