// Code generated by encx-gen. DO NOT EDIT.
// Source: partner.go
// Generated: 2025-10-09T09:35:59+02:00

package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hengadev/encx"
	"github.com/hengadev/errsx"
)

// PartnerEncx represents the encrypted version of Partner
type PartnerEncx struct {
	ID uuid.UUID `db:"id" json:"id"`

	UserID uuid.UUID `db:"userid" json:"userid"`

	IsVerified bool `db:"isverified" json:"isverified"`

	VerifiedByUserID *uuid.UUID `db:"verifiedbyuserid" json:"verifiedbyuserid"`

	CreatedAt time.Time `db:"createdat" json:"createdat"`

	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`

	User *UserEncx `db:"user" json:"user"`

	Specializations []SpecializationResponse `db:"specializations" json:"specializations"`

	CategoryIDs []uuid.UUID `db:"category_ids" json:"category_ids"`

	ProductIDs []uuid.UUID `db:"product_ids" json:"product_ids"`

	BioEncrypted []byte `db:"bio_encrypted" json:"bio_encrypted"`

	ExperienceEncrypted []byte `db:"experience_encrypted" json:"experience_encrypted"`

	CertificationsEncrypted []byte `db:"certifications_encrypted" json:"certifications_encrypted"`

	VerifiedAtEncrypted []byte `db:"verifiedat_encrypted" json:"verifiedat_encrypted"`

	// Essential encryption fields
	DEKEncrypted []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion   int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessPartnerEncx encrypts and hashes fields based on encx tags
func ProcessPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *Partner) (*PartnerEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &PartnerEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.UserID = source.UserID

	result.IsVerified = source.IsVerified

	result.VerifiedByUserID = source.VerifiedByUserID

	result.CreatedAt = source.CreatedAt

	result.UpdatedAt = source.UpdatedAt

	// Process User field if present
	if source.User != nil {
		processedUser, err := ProcessUserEncx(ctx, crypto, source.User)
		if err != nil {
			errs.Set("User processing", err)
		} else {
			result.User = processedUser
		}
	}

	result.Specializations = source.Specializations

	result.CategoryIDs = source.CategoryIDs

	result.ProductIDs = source.ProductIDs

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	// Process Bio (encrypt)
	if source.Bio != "" {
		BioBytes, err := encx.SerializeValue(source.Bio)
		if err != nil {
			errs.Set("Bio serialization", err)
		} else {
			result.BioEncrypted, err = crypto.EncryptData(ctx, BioBytes, dek)
			if err != nil {
				errs.Set("Bio encryption", err)
			}
		}
	}

	// Process Experience (encrypt)
	if source.Experience != "" {
		ExperienceBytes, err := encx.SerializeValue(source.Experience)
		if err != nil {
			errs.Set("Experience serialization", err)
		} else {
			result.ExperienceEncrypted, err = crypto.EncryptData(ctx, ExperienceBytes, dek)
			if err != nil {
				errs.Set("Experience encryption", err)
			}
		}
	}

	// Process Certifications (encrypt)
	if source.Certifications != nil {
		CertificationsBytes, err := encx.SerializeValue(source.Certifications)
		if err != nil {
			errs.Set("Certifications serialization", err)
		} else {
			result.CertificationsEncrypted, err = crypto.EncryptData(ctx, CertificationsBytes, dek)
			if err != nil {
				errs.Set("Certifications encryption", err)
			}
		}
	}

	// Process VerifiedAt (encrypt)
	if source.VerifiedAt != nil {
		VerifiedAtBytes, err := encx.SerializeValue(source.VerifiedAt)
		if err != nil {
			errs.Set("VerifiedAt serialization", err)
		} else {
			result.VerifiedAtEncrypted, err = crypto.EncryptData(ctx, VerifiedAtBytes, dek)
			if err != nil {
				errs.Set("VerifiedAt encryption", err)
			}
		}
	}

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptPartnerEncx decrypts the encrypted struct back to original
func DecryptPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *PartnerEncx) (*Partner, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Partner{}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.UserID = source.UserID

	result.IsVerified = source.IsVerified

	result.VerifiedByUserID = source.VerifiedByUserID

	result.CreatedAt = source.CreatedAt

	result.UpdatedAt = source.UpdatedAt

	// Process User field if present
	if source.User != nil {
		processedUser, err := DecryptUserEncx(ctx, crypto, source.User)
		if err != nil {
			errs.Set("User processing", err)
		} else {
			result.User = processedUser
		}
	}

	result.Specializations = source.Specializations

	result.CategoryIDs = source.CategoryIDs

	result.ProductIDs = source.ProductIDs

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	// Decrypt Bio
	if len(source.BioEncrypted) > 0 {
		BioBytes, err := crypto.DecryptData(ctx, source.BioEncrypted, dek)
		if err != nil {
			errs.Set("Bio decryption", err)
		} else {
			err = encx.DeserializeValue(BioBytes, &result.Bio)
			if err != nil {
				errs.Set("Bio deserialization", err)
			}
		}
	}

	// Decrypt Experience
	if len(source.ExperienceEncrypted) > 0 {
		ExperienceBytes, err := crypto.DecryptData(ctx, source.ExperienceEncrypted, dek)
		if err != nil {
			errs.Set("Experience decryption", err)
		} else {
			err = encx.DeserializeValue(ExperienceBytes, &result.Experience)
			if err != nil {
				errs.Set("Experience deserialization", err)
			}
		}
	}

	// Decrypt Certifications
	if len(source.CertificationsEncrypted) > 0 {
		CertificationsBytes, err := crypto.DecryptData(ctx, source.CertificationsEncrypted, dek)
		if err != nil {
			errs.Set("Certifications decryption", err)
		} else {
			err = encx.DeserializeValue(CertificationsBytes, &result.Certifications)
			if err != nil {
				errs.Set("Certifications deserialization", err)
			}
		}
	}

	// Decrypt VerifiedAt
	if len(source.VerifiedAtEncrypted) > 0 {
		VerifiedAtBytes, err := crypto.DecryptData(ctx, source.VerifiedAtEncrypted, dek)
		if err != nil {
			errs.Set("VerifiedAt decryption", err)
		} else {
			err = encx.DeserializeValue(VerifiedAtBytes, &result.VerifiedAt)
			if err != nil {
				errs.Set("VerifiedAt deserialization", err)
			}
		}
	}

	return result, errs.AsError()
}
