// Code generated by encx-gen. DO NOT EDIT.
// Source: partner.go
// Generated: 2025-10-30T11:49:17+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/encx"
	"github.com/hengadev/errsx"

	"github.com/google/uuid"
)

// PartnerEncx represents the encrypted version of Partner
type PartnerEncx struct {
	UserID uuid.UUID `db:"userid" json:"userid"`

	CreatedAt time.Time `db:"createdat" json:"createdat"`

	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`

	StripeAccountStatus StripeAccountStatus `db:"stripeaccountstatus" json:"stripeaccountstatus"`

	StripeOnboardingComplete bool `db:"stripeonboardingcomplete" json:"stripeonboardingcomplete"`

	BioEncrypted []byte `db:"bio_encrypted" json:"bio_encrypted"`

	ExperienceEncrypted []byte `db:"experience_encrypted" json:"experience_encrypted"`

	CertificationsEncrypted []byte `db:"certifications_encrypted" json:"certifications_encrypted"`

	CategoryIDsEncrypted []byte `db:"categoryids_encrypted" json:"categoryids_encrypted"`

	ProductIDsEncrypted []byte `db:"productids_encrypted" json:"productids_encrypted"`

	StripeConnectedAccountIDEncrypted []byte `db:"stripeconnectedaccountid_encrypted" json:"stripeconnectedaccountid_encrypted"`

	// Essential encryption fields
	DEKEncrypted []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion   int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessPartnerEncx encrypts and hashes fields based on encx tags
func ProcessPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *Partner) (*PartnerEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &PartnerEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)

	result.UserID = source.UserID

	result.CreatedAt = source.CreatedAt

	result.UpdatedAt = source.UpdatedAt

	result.StripeAccountStatus = source.StripeAccountStatus

	result.StripeOnboardingComplete = source.StripeOnboardingComplete

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	// Process Bio (encrypt)
	BioBytes, err := encx.SerializeValue(source.Bio)
	if err != nil {
		errs.Set("Bio serialization", err)
	} else {
		result.BioEncrypted, err = crypto.EncryptData(ctx, BioBytes, dek)
		if err != nil {
			errs.Set("Bio encryption", err)
		}
	}

	// Process Experience (encrypt)
	ExperienceBytes, err := encx.SerializeValue(source.Experience)
	if err != nil {
		errs.Set("Experience serialization", err)
	} else {
		result.ExperienceEncrypted, err = crypto.EncryptData(ctx, ExperienceBytes, dek)
		if err != nil {
			errs.Set("Experience encryption", err)
		}
	}

	// Process Certifications (encrypt)
	CertificationsBytes, err := encx.SerializeValue(source.Certifications)
	if err != nil {
		errs.Set("Certifications serialization", err)
	} else {
		result.CertificationsEncrypted, err = crypto.EncryptData(ctx, CertificationsBytes, dek)
		if err != nil {
			errs.Set("Certifications encryption", err)
		}
	}

	// Process CategoryIDs (encrypt)
	if source.CategoryIDs != nil {
		CategoryIDsBytes, err := encx.SerializeValue(source.CategoryIDs)
		if err != nil {
			errs.Set("CategoryIDs serialization", err)
		} else {
			result.CategoryIDsEncrypted, err = crypto.EncryptData(ctx, CategoryIDsBytes, dek)
			if err != nil {
				errs.Set("CategoryIDs encryption", err)
			}
		}
	}

	// Process ProductIDs (encrypt)
	if source.ProductIDs != nil {
		ProductIDsBytes, err := encx.SerializeValue(source.ProductIDs)
		if err != nil {
			errs.Set("ProductIDs serialization", err)
		} else {
			result.ProductIDsEncrypted, err = crypto.EncryptData(ctx, ProductIDsBytes, dek)
			if err != nil {
				errs.Set("ProductIDs encryption", err)
			}
		}
	}

	// Process StripeConnectedAccountID (encrypt)
	StripeConnectedAccountIDBytes, err := encx.SerializeValue(source.StripeConnectedAccountID)
	if err != nil {
		errs.Set("StripeConnectedAccountID serialization", err)
	} else {
		result.StripeConnectedAccountIDEncrypted, err = crypto.EncryptData(ctx, StripeConnectedAccountIDBytes, dek)
		if err != nil {
			errs.Set("StripeConnectedAccountID encryption", err)
		}
	}

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptPartnerEncx decrypts the encrypted struct back to original
func DecryptPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *PartnerEncx) (*Partner, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Partner{}

	// Copy plain fields (non-encx fields)

	result.UserID = source.UserID

	result.CreatedAt = source.CreatedAt

	result.UpdatedAt = source.UpdatedAt

	result.StripeAccountStatus = source.StripeAccountStatus

	result.StripeOnboardingComplete = source.StripeOnboardingComplete

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	// Decrypt Bio
	if len(source.BioEncrypted) > 0 {
		BioBytes, err := crypto.DecryptData(ctx, source.BioEncrypted, dek)
		if err != nil {
			errs.Set("Bio decryption", err)
		} else {
			err = encx.DeserializeValue(BioBytes, &result.Bio)
			if err != nil {
				errs.Set("Bio deserialization", err)
			}
		}
	}

	// Decrypt Experience
	if len(source.ExperienceEncrypted) > 0 {
		ExperienceBytes, err := crypto.DecryptData(ctx, source.ExperienceEncrypted, dek)
		if err != nil {
			errs.Set("Experience decryption", err)
		} else {
			err = encx.DeserializeValue(ExperienceBytes, &result.Experience)
			if err != nil {
				errs.Set("Experience deserialization", err)
			}
		}
	}

	// Decrypt Certifications
	if len(source.CertificationsEncrypted) > 0 {
		CertificationsBytes, err := crypto.DecryptData(ctx, source.CertificationsEncrypted, dek)
		if err != nil {
			errs.Set("Certifications decryption", err)
		} else {
			err = encx.DeserializeValue(CertificationsBytes, &result.Certifications)
			if err != nil {
				errs.Set("Certifications deserialization", err)
			}
		}
	}

	// Decrypt CategoryIDs
	if len(source.CategoryIDsEncrypted) > 0 {
		CategoryIDsBytes, err := crypto.DecryptData(ctx, source.CategoryIDsEncrypted, dek)
		if err != nil {
			errs.Set("CategoryIDs decryption", err)
		} else {
			err = encx.DeserializeValue(CategoryIDsBytes, &result.CategoryIDs)
			if err != nil {
				errs.Set("CategoryIDs deserialization", err)
			}
		}
	}

	// Decrypt ProductIDs
	if len(source.ProductIDsEncrypted) > 0 {
		ProductIDsBytes, err := crypto.DecryptData(ctx, source.ProductIDsEncrypted, dek)
		if err != nil {
			errs.Set("ProductIDs decryption", err)
		} else {
			err = encx.DeserializeValue(ProductIDsBytes, &result.ProductIDs)
			if err != nil {
				errs.Set("ProductIDs deserialization", err)
			}
		}
	}

	// Decrypt StripeConnectedAccountID
	if len(source.StripeConnectedAccountIDEncrypted) > 0 {
		StripeConnectedAccountIDBytes, err := crypto.DecryptData(ctx, source.StripeConnectedAccountIDEncrypted, dek)
		if err != nil {
			errs.Set("StripeConnectedAccountID decryption", err)
		} else {
			err = encx.DeserializeValue(StripeConnectedAccountIDBytes, &result.StripeConnectedAccountID)
			if err != nil {
				errs.Set("StripeConnectedAccountID deserialization", err)
			}
		}
	}

	return result, errs.AsError()
}
