// Code generated by encx-gen. DO NOT EDIT.
// Source: partner.go
// Generated: 2026-04-27T17:51:29+02:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// PartnerEncx represents the encrypted version of Partner
type PartnerEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	UserID uuid.UUID `db:"userid" json:"userid"`
	
	Bio string `db:"bio" json:"bio"`
	
	Experience string `db:"experience" json:"experience"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	CategoryIDs []uuid.UUID `db:"categoryids" json:"categoryids"`
	
	ProductIDs []uuid.UUID `db:"productids" json:"productids"`
	
	StripeAccountStatus StripeAccountStatus `db:"stripeaccountstatus" json:"stripeaccountstatus"`
	
	StripeOnboardingComplete bool `db:"stripeonboardingcomplete" json:"stripeonboardingcomplete"`
	
	
	StripeConnectedAccountIDEncrypted []byte `db:"stripeconnectedaccountid_encrypted" json:"stripeconnectedaccountid_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessPartnerEncx encrypts and hashes fields based on encx tags
func ProcessPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *Partner) (*PartnerEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &PartnerEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.UserID = source.UserID
	
	result.Bio = source.Bio
	
	result.Experience = source.Experience
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.CategoryIDs = source.CategoryIDs
	
	result.ProductIDs = source.ProductIDs
	
	result.StripeAccountStatus = source.StripeAccountStatus
	
	result.StripeOnboardingComplete = source.StripeOnboardingComplete
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process StripeConnectedAccountID (encrypt)
	StripeConnectedAccountIDBytes, err := encx.SerializeValue(source.StripeConnectedAccountID)
	if err != nil {
		errs.Set("StripeConnectedAccountID serialization", err)
	} else {
		result.StripeConnectedAccountIDEncrypted, err = crypto.EncryptData(ctx, StripeConnectedAccountIDBytes, dek)
		if err != nil {
			errs.Set("StripeConnectedAccountID encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptPartnerEncx decrypts the encrypted struct back to original
func DecryptPartnerEncx(ctx context.Context, crypto encx.CryptoService, source *PartnerEncx) (*Partner, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Partner{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.UserID = source.UserID
	
	result.Bio = source.Bio
	
	result.Experience = source.Experience
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.CategoryIDs = source.CategoryIDs
	
	result.ProductIDs = source.ProductIDs
	
	result.StripeAccountStatus = source.StripeAccountStatus
	
	result.StripeOnboardingComplete = source.StripeOnboardingComplete
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt StripeConnectedAccountID
	if len(source.StripeConnectedAccountIDEncrypted) > 0 {
		StripeConnectedAccountIDBytes, err := crypto.DecryptData(ctx, source.StripeConnectedAccountIDEncrypted, dek)
		if err != nil {
			errs.Set("StripeConnectedAccountID decryption", err)
		} else {
			err = encx.DeserializeValue(StripeConnectedAccountIDBytes, &result.StripeConnectedAccountID)
			if err != nil {
				errs.Set("StripeConnectedAccountID deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
