// Code generated by encx-gen. DO NOT EDIT.
// Source: specialization.go
// Generated: 2025-10-09T09:35:59+02:00

package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"

)

// SpecializationEncx represents the encrypted version of Specialization
type SpecializationEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	IsActive bool `db:"isactive" json:"isactive"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	NameEncrypted []byte `db:"name_encrypted" json:"name_encrypted"`
	
	DisplayNameEncrypted []byte `db:"displayname_encrypted" json:"displayname_encrypted"`
	
	DescriptionEncrypted []byte `db:"description_encrypted" json:"description_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessSpecializationEncx encrypts and hashes fields based on encx tags
func ProcessSpecializationEncx(ctx context.Context, crypto encx.CryptoService, source *Specialization) (*SpecializationEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SpecializationEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Name (encrypt)
	if source.Name != "" {
		NameBytes, err := encx.SerializeValue(source.Name)
		if err != nil {
			errs.Set("Name serialization", err)
		} else {
			result.NameEncrypted, err = crypto.EncryptData(ctx, NameBytes, dek)
			if err != nil {
				errs.Set("Name encryption", err)
			}
		}
	}
	
	
	// Process DisplayName (encrypt)
	if source.DisplayName != "" {
		DisplayNameBytes, err := encx.SerializeValue(source.DisplayName)
		if err != nil {
			errs.Set("DisplayName serialization", err)
		} else {
			result.DisplayNameEncrypted, err = crypto.EncryptData(ctx, DisplayNameBytes, dek)
			if err != nil {
				errs.Set("DisplayName encryption", err)
			}
		}
	}
	
	
	// Process Description (encrypt)
	if source.Description != "" {
		DescriptionBytes, err := encx.SerializeValue(source.Description)
		if err != nil {
			errs.Set("Description serialization", err)
		} else {
			result.DescriptionEncrypted, err = crypto.EncryptData(ctx, DescriptionBytes, dek)
			if err != nil {
				errs.Set("Description encryption", err)
			}
		}
	}
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptSpecializationEncx decrypts the encrypted struct back to original
func DecryptSpecializationEncx(ctx context.Context, crypto encx.CryptoService, source *SpecializationEncx) (*Specialization, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Specialization{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsActive = source.IsActive
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Name
	if len(source.NameEncrypted) > 0 {
		NameBytes, err := crypto.DecryptData(ctx, source.NameEncrypted, dek)
		if err != nil {
			errs.Set("Name decryption", err)
		} else {
			err = encx.DeserializeValue(NameBytes, &result.Name)
			if err != nil {
				errs.Set("Name deserialization", err)
			}
		}
	}
	
	
	// Decrypt DisplayName
	if len(source.DisplayNameEncrypted) > 0 {
		DisplayNameBytes, err := crypto.DecryptData(ctx, source.DisplayNameEncrypted, dek)
		if err != nil {
			errs.Set("DisplayName decryption", err)
		} else {
			err = encx.DeserializeValue(DisplayNameBytes, &result.DisplayName)
			if err != nil {
				errs.Set("DisplayName deserialization", err)
			}
		}
	}
	
	
	// Decrypt Description
	if len(source.DescriptionEncrypted) > 0 {
		DescriptionBytes, err := crypto.DecryptData(ctx, source.DescriptionEncrypted, dek)
		if err != nil {
			errs.Set("Description decryption", err)
		} else {
			err = encx.DeserializeValue(DescriptionBytes, &result.Description)
			if err != nil {
				errs.Set("Description deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
