// Code generated by encx-gen. DO NOT EDIT.
// Source: user.go
// Generated: 2025-11-17T22:32:25+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// UserEncx represents the encrypted version of User
type UserEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	State UserState `db:"state" json:"state"`
	
	
	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`
	
	EmailHash string `db:"email_hash" json:"email_hash"`
	
	PasswordHashSecure string `db:"password_hash_secure" json:"password_hash_secure"`
	
	PictureEncrypted []byte `db:"picture_encrypted" json:"picture_encrypted"`
	
	CreatedAtEncrypted []byte `db:"createdat_encrypted" json:"createdat_encrypted"`
	
	LoggedInAtEncrypted []byte `db:"loggedinat_encrypted" json:"loggedinat_encrypted"`
	
	RoleEncrypted []byte `db:"role_encrypted" json:"role_encrypted"`
	
	BirthDateEncrypted []byte `db:"birthdate_encrypted" json:"birthdate_encrypted"`
	
	LastNameEncrypted []byte `db:"lastname_encrypted" json:"lastname_encrypted"`
	
	FirstNameEncrypted []byte `db:"firstname_encrypted" json:"firstname_encrypted"`
	
	GenderEncrypted []byte `db:"gender_encrypted" json:"gender_encrypted"`
	
	TelephoneEncrypted []byte `db:"telephone_encrypted" json:"telephone_encrypted"`
	
	TelephoneHash string `db:"telephone_hash" json:"telephone_hash"`
	
	PostalCodeEncrypted []byte `db:"postalcode_encrypted" json:"postalcode_encrypted"`
	
	CityEncrypted []byte `db:"city_encrypted" json:"city_encrypted"`
	
	Address1Encrypted []byte `db:"address1_encrypted" json:"address1_encrypted"`
	
	Address2Encrypted []byte `db:"address2_encrypted" json:"address2_encrypted"`
	
	GoogleIDEncrypted []byte `db:"googleid_encrypted" json:"googleid_encrypted"`
	
	AppleIDEncrypted []byte `db:"appleid_encrypted" json:"appleid_encrypted"`
	
	StripeCustomerIDEncrypted []byte `db:"stripecustomerid_encrypted" json:"stripecustomerid_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessUserEncx encrypts and hashes fields based on encx tags
func ProcessUserEncx(ctx context.Context, crypto encx.CryptoService, source *User) (*UserEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &UserEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.State = source.State
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Email (encrypt + hash_basic)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
		if err != nil {
			errs.Set("Email encryption", err)
		}
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)
		
	}
	
	
	
	// Process Password (hash_secure)
	PasswordBytes, err := encx.SerializeValue(source.Password)
	if err != nil {
		errs.Set("Password serialization", err)
	} else {
		result.PasswordHashSecure, err = crypto.HashSecure(ctx, PasswordBytes)
		if err != nil {
			errs.Set("Password secure hash", err)
		}
	}
	
	
	
	// Process Picture (encrypt)
	PictureBytes, err := encx.SerializeValue(source.Picture)
	if err != nil {
		errs.Set("Picture serialization", err)
	} else {
		result.PictureEncrypted, err = crypto.EncryptData(ctx, PictureBytes, dek)
		if err != nil {
			errs.Set("Picture encryption", err)
		}
	}
	
	
	
	// Process CreatedAt (encrypt)
	if !source.CreatedAt.IsZero() {
	CreatedAtBytes, err := encx.SerializeValue(source.CreatedAt)
	if err != nil {
		errs.Set("CreatedAt serialization", err)
	} else {
		result.CreatedAtEncrypted, err = crypto.EncryptData(ctx, CreatedAtBytes, dek)
		if err != nil {
			errs.Set("CreatedAt encryption", err)
		}
	}
	}
	
	
	
	// Process LoggedInAt (encrypt)
	if !source.LoggedInAt.IsZero() {
	LoggedInAtBytes, err := encx.SerializeValue(source.LoggedInAt)
	if err != nil {
		errs.Set("LoggedInAt serialization", err)
	} else {
		result.LoggedInAtEncrypted, err = crypto.EncryptData(ctx, LoggedInAtBytes, dek)
		if err != nil {
			errs.Set("LoggedInAt encryption", err)
		}
	}
	}
	
	
	
	// Process Role (encrypt)
	RoleBytes, err := encx.SerializeValue(source.Role)
	if err != nil {
		errs.Set("Role serialization", err)
	} else {
		result.RoleEncrypted, err = crypto.EncryptData(ctx, RoleBytes, dek)
		if err != nil {
			errs.Set("Role encryption", err)
		}
	}
	
	
	
	// Process BirthDate (encrypt)
	if !source.BirthDate.IsZero() {
	BirthDateBytes, err := encx.SerializeValue(source.BirthDate)
	if err != nil {
		errs.Set("BirthDate serialization", err)
	} else {
		result.BirthDateEncrypted, err = crypto.EncryptData(ctx, BirthDateBytes, dek)
		if err != nil {
			errs.Set("BirthDate encryption", err)
		}
	}
	}
	
	
	
	// Process LastName (encrypt)
	LastNameBytes, err := encx.SerializeValue(source.LastName)
	if err != nil {
		errs.Set("LastName serialization", err)
	} else {
		result.LastNameEncrypted, err = crypto.EncryptData(ctx, LastNameBytes, dek)
		if err != nil {
			errs.Set("LastName encryption", err)
		}
	}
	
	
	
	// Process FirstName (encrypt)
	FirstNameBytes, err := encx.SerializeValue(source.FirstName)
	if err != nil {
		errs.Set("FirstName serialization", err)
	} else {
		result.FirstNameEncrypted, err = crypto.EncryptData(ctx, FirstNameBytes, dek)
		if err != nil {
			errs.Set("FirstName encryption", err)
		}
	}
	
	
	
	// Process Gender (encrypt)
	GenderBytes, err := encx.SerializeValue(source.Gender)
	if err != nil {
		errs.Set("Gender serialization", err)
	} else {
		result.GenderEncrypted, err = crypto.EncryptData(ctx, GenderBytes, dek)
		if err != nil {
			errs.Set("Gender encryption", err)
		}
	}
	
	
	
	// Process Telephone (encrypt + hash_basic)
	TelephoneBytes, err := encx.SerializeValue(source.Telephone)
	if err != nil {
		errs.Set("Telephone serialization", err)
	} else {
		result.TelephoneEncrypted, err = crypto.EncryptData(ctx, TelephoneBytes, dek)
		if err != nil {
			errs.Set("Telephone encryption", err)
		}
		result.TelephoneHash = crypto.HashBasic(ctx, TelephoneBytes)
		
	}
	
	
	
	// Process PostalCode (encrypt)
	PostalCodeBytes, err := encx.SerializeValue(source.PostalCode)
	if err != nil {
		errs.Set("PostalCode serialization", err)
	} else {
		result.PostalCodeEncrypted, err = crypto.EncryptData(ctx, PostalCodeBytes, dek)
		if err != nil {
			errs.Set("PostalCode encryption", err)
		}
	}
	
	
	
	// Process City (encrypt)
	CityBytes, err := encx.SerializeValue(source.City)
	if err != nil {
		errs.Set("City serialization", err)
	} else {
		result.CityEncrypted, err = crypto.EncryptData(ctx, CityBytes, dek)
		if err != nil {
			errs.Set("City encryption", err)
		}
	}
	
	
	
	// Process Address1 (encrypt)
	Address1Bytes, err := encx.SerializeValue(source.Address1)
	if err != nil {
		errs.Set("Address1 serialization", err)
	} else {
		result.Address1Encrypted, err = crypto.EncryptData(ctx, Address1Bytes, dek)
		if err != nil {
			errs.Set("Address1 encryption", err)
		}
	}
	
	
	
	// Process Address2 (encrypt)
	Address2Bytes, err := encx.SerializeValue(source.Address2)
	if err != nil {
		errs.Set("Address2 serialization", err)
	} else {
		result.Address2Encrypted, err = crypto.EncryptData(ctx, Address2Bytes, dek)
		if err != nil {
			errs.Set("Address2 encryption", err)
		}
	}
	
	
	
	// Process GoogleID (encrypt)
	GoogleIDBytes, err := encx.SerializeValue(source.GoogleID)
	if err != nil {
		errs.Set("GoogleID serialization", err)
	} else {
		result.GoogleIDEncrypted, err = crypto.EncryptData(ctx, GoogleIDBytes, dek)
		if err != nil {
			errs.Set("GoogleID encryption", err)
		}
	}
	
	
	
	// Process AppleID (encrypt)
	AppleIDBytes, err := encx.SerializeValue(source.AppleID)
	if err != nil {
		errs.Set("AppleID serialization", err)
	} else {
		result.AppleIDEncrypted, err = crypto.EncryptData(ctx, AppleIDBytes, dek)
		if err != nil {
			errs.Set("AppleID encryption", err)
		}
	}
	
	
	
	// Process StripeCustomerID (encrypt)
	StripeCustomerIDBytes, err := encx.SerializeValue(source.StripeCustomerID)
	if err != nil {
		errs.Set("StripeCustomerID serialization", err)
	} else {
		result.StripeCustomerIDEncrypted, err = crypto.EncryptData(ctx, StripeCustomerIDBytes, dek)
		if err != nil {
			errs.Set("StripeCustomerID encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptUserEncx decrypts the encrypted struct back to original
func DecryptUserEncx(ctx context.Context, crypto encx.CryptoService, source *UserEncx) (*User, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &User{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.State = source.State
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}
	
	
	// Decrypt Picture
	if len(source.PictureEncrypted) > 0 {
		PictureBytes, err := crypto.DecryptData(ctx, source.PictureEncrypted, dek)
		if err != nil {
			errs.Set("Picture decryption", err)
		} else {
			err = encx.DeserializeValue(PictureBytes, &result.Picture)
			if err != nil {
				errs.Set("Picture deserialization", err)
			}
		}
	}
	
	
	// Decrypt CreatedAt
	if len(source.CreatedAtEncrypted) > 0 {
		CreatedAtBytes, err := crypto.DecryptData(ctx, source.CreatedAtEncrypted, dek)
		if err != nil {
			errs.Set("CreatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(CreatedAtBytes, &result.CreatedAt)
			if err != nil {
				errs.Set("CreatedAt deserialization", err)
			}
		}
	}
	
	
	// Decrypt LoggedInAt
	if len(source.LoggedInAtEncrypted) > 0 {
		LoggedInAtBytes, err := crypto.DecryptData(ctx, source.LoggedInAtEncrypted, dek)
		if err != nil {
			errs.Set("LoggedInAt decryption", err)
		} else {
			err = encx.DeserializeValue(LoggedInAtBytes, &result.LoggedInAt)
			if err != nil {
				errs.Set("LoggedInAt deserialization", err)
			}
		}
	}
	
	
	// Decrypt Role
	if len(source.RoleEncrypted) > 0 {
		RoleBytes, err := crypto.DecryptData(ctx, source.RoleEncrypted, dek)
		if err != nil {
			errs.Set("Role decryption", err)
		} else {
			err = encx.DeserializeValue(RoleBytes, &result.Role)
			if err != nil {
				errs.Set("Role deserialization", err)
			}
		}
	}
	
	
	// Decrypt BirthDate
	if len(source.BirthDateEncrypted) > 0 {
		BirthDateBytes, err := crypto.DecryptData(ctx, source.BirthDateEncrypted, dek)
		if err != nil {
			errs.Set("BirthDate decryption", err)
		} else {
			err = encx.DeserializeValue(BirthDateBytes, &result.BirthDate)
			if err != nil {
				errs.Set("BirthDate deserialization", err)
			}
		}
	}
	
	
	// Decrypt LastName
	if len(source.LastNameEncrypted) > 0 {
		LastNameBytes, err := crypto.DecryptData(ctx, source.LastNameEncrypted, dek)
		if err != nil {
			errs.Set("LastName decryption", err)
		} else {
			err = encx.DeserializeValue(LastNameBytes, &result.LastName)
			if err != nil {
				errs.Set("LastName deserialization", err)
			}
		}
	}
	
	
	// Decrypt FirstName
	if len(source.FirstNameEncrypted) > 0 {
		FirstNameBytes, err := crypto.DecryptData(ctx, source.FirstNameEncrypted, dek)
		if err != nil {
			errs.Set("FirstName decryption", err)
		} else {
			err = encx.DeserializeValue(FirstNameBytes, &result.FirstName)
			if err != nil {
				errs.Set("FirstName deserialization", err)
			}
		}
	}
	
	
	// Decrypt Gender
	if len(source.GenderEncrypted) > 0 {
		GenderBytes, err := crypto.DecryptData(ctx, source.GenderEncrypted, dek)
		if err != nil {
			errs.Set("Gender decryption", err)
		} else {
			err = encx.DeserializeValue(GenderBytes, &result.Gender)
			if err != nil {
				errs.Set("Gender deserialization", err)
			}
		}
	}
	
	
	// Decrypt Telephone
	if len(source.TelephoneEncrypted) > 0 {
		TelephoneBytes, err := crypto.DecryptData(ctx, source.TelephoneEncrypted, dek)
		if err != nil {
			errs.Set("Telephone decryption", err)
		} else {
			err = encx.DeserializeValue(TelephoneBytes, &result.Telephone)
			if err != nil {
				errs.Set("Telephone deserialization", err)
			}
		}
	}
	
	
	// Decrypt PostalCode
	if len(source.PostalCodeEncrypted) > 0 {
		PostalCodeBytes, err := crypto.DecryptData(ctx, source.PostalCodeEncrypted, dek)
		if err != nil {
			errs.Set("PostalCode decryption", err)
		} else {
			err = encx.DeserializeValue(PostalCodeBytes, &result.PostalCode)
			if err != nil {
				errs.Set("PostalCode deserialization", err)
			}
		}
	}
	
	
	// Decrypt City
	if len(source.CityEncrypted) > 0 {
		CityBytes, err := crypto.DecryptData(ctx, source.CityEncrypted, dek)
		if err != nil {
			errs.Set("City decryption", err)
		} else {
			err = encx.DeserializeValue(CityBytes, &result.City)
			if err != nil {
				errs.Set("City deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address1
	if len(source.Address1Encrypted) > 0 {
		Address1Bytes, err := crypto.DecryptData(ctx, source.Address1Encrypted, dek)
		if err != nil {
			errs.Set("Address1 decryption", err)
		} else {
			err = encx.DeserializeValue(Address1Bytes, &result.Address1)
			if err != nil {
				errs.Set("Address1 deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address2
	if len(source.Address2Encrypted) > 0 {
		Address2Bytes, err := crypto.DecryptData(ctx, source.Address2Encrypted, dek)
		if err != nil {
			errs.Set("Address2 decryption", err)
		} else {
			err = encx.DeserializeValue(Address2Bytes, &result.Address2)
			if err != nil {
				errs.Set("Address2 deserialization", err)
			}
		}
	}
	
	
	// Decrypt GoogleID
	if len(source.GoogleIDEncrypted) > 0 {
		GoogleIDBytes, err := crypto.DecryptData(ctx, source.GoogleIDEncrypted, dek)
		if err != nil {
			errs.Set("GoogleID decryption", err)
		} else {
			err = encx.DeserializeValue(GoogleIDBytes, &result.GoogleID)
			if err != nil {
				errs.Set("GoogleID deserialization", err)
			}
		}
	}
	
	
	// Decrypt AppleID
	if len(source.AppleIDEncrypted) > 0 {
		AppleIDBytes, err := crypto.DecryptData(ctx, source.AppleIDEncrypted, dek)
		if err != nil {
			errs.Set("AppleID decryption", err)
		} else {
			err = encx.DeserializeValue(AppleIDBytes, &result.AppleID)
			if err != nil {
				errs.Set("AppleID deserialization", err)
			}
		}
	}
	
	
	// Decrypt StripeCustomerID
	if len(source.StripeCustomerIDEncrypted) > 0 {
		StripeCustomerIDBytes, err := crypto.DecryptData(ctx, source.StripeCustomerIDEncrypted, dek)
		if err != nil {
			errs.Set("StripeCustomerID decryption", err)
		} else {
			err = encx.DeserializeValue(StripeCustomerIDBytes, &result.StripeCustomerID)
			if err != nil {
				errs.Set("StripeCustomerID deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
