staging-plan:
	terraform plan -var-file="staging.tfvars"

prod-plan:
	terraform plan -var-file="prod.tfvars"

staging-apply:
	terraform apply -var-file="staging.tfvars"

prod-apply:
	terraform apply -var-file="prod.tfvars"
