// Mock data for categories and products in development mode

export const mockCategories = [
    {
        id: "cat-1",
        name: "Bodywork & Massage",
        description: "Restore balance and alleviate tension with our therapeutic bodywork sessions. Tailored to your specific recovery needs.",
        status: "published" as const,
        metadata: {},
        createdAt: "2024-12-01T10:00:00Z",
        updatedAt: "2025-01-15T14:30:00Z",
        images: [
            {
                id: "img-cat-1",
                parent_id: "cat-1",
                parent_type: "category",
                url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop",
                title: "Bodywork & Massage",
                is_active: true,
                created_at: "2024-12-01T10:00:00Z",
            }
        ]
    },
    {
        id: "cat-2",
        name: "Mindset Coaching",
        description: "Transform your mindset and unlock your potential with personalized coaching sessions designed for high-performers.",
        status: "published" as const,
        metadata: {},
        createdAt: "2024-12-02T11:00:00Z",
        updatedAt: "2025-01-16T09:00:00Z",
        images: [
            {
                id: "img-cat-2",
                parent_id: "cat-2",
                parent_type: "category",
                url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop",
                title: "Mindset Coaching",
                is_active: true,
                created_at: "2024-12-02T11:00:00Z",
            }
        ]
    },
    {
        id: "cat-3",
        name: "Physical Training",
        description: "Build strength, improve mobility, and optimize your physical performance with expert-guided training programs.",
        status: "published" as const,
        metadata: {},
        createdAt: "2024-12-03T09:30:00Z",
        updatedAt: "2025-01-17T16:45:00Z",
        images: [
            {
                id: "img-cat-3",
                parent_id: "cat-3",
                parent_type: "category",
                url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop",
                title: "Physical Training",
                is_active: true,
                created_at: "2024-12-03T09:30:00Z",
            }
        ]
    },
    {
        id: "cat-4",
        name: "Wellness & Recovery",
        description: "Comprehensive wellness solutions focused on recovery, rejuvenation, and maintaining optimal health.",
        status: "draft" as const,
        metadata: {},
        createdAt: "2024-12-04T14:00:00Z",
        updatedAt: "2025-01-18T11:20:00Z",
        images: []
    },
];

export const mockProducts = [
    {
        id: "prod-1",
        name: "Deep Tissue Therapy",
        description: "Focus on realigning deep layers of muscle and connective tissue. It is especially helpful for chronic aches and pain in contracted areas.",
        category: "cat-1",
        duration: 60,
        status: "published" as const,
        availability: "in-person" as const,
        bufferTime: 10,
        cancellationHours: 24,
        stripeProductId: "prod_stripe_1",
        metadata: { intensity: "high", targetAreas: ["back", "shoulders", "neck"] },
        createdAt: "2025-01-01T10:00:00Z",
        updatedAt: "2025-01-15T14:30:00Z",
        images: [
            {
                id: "img-prod-1",
                parent_id: "prod-1",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&auto=format&fit=crop",
                title: "Deep Tissue Therapy",
                is_active: true,
                created_at: "2025-01-01T10:00:00Z",
            }
        ]
    },
    {
        id: "prod-2",
        name: "Lymphatic Drainage",
        description: "A gentle massage that encourages the movement of lymph fluids around the body. Helps remove waste and toxins.",
        category: "cat-1",
        duration: 60,
        status: "published" as const,
        availability: "in-person" as const,
        bufferTime: 10,
        cancellationHours: 24,
        stripeProductId: "prod_stripe_2",
        metadata: { intensity: "low", technique: "gentle" },
        createdAt: "2025-01-02T11:00:00Z",
        updatedAt: "2025-01-16T09:00:00Z",
        images: [
            {
                id: "img-prod-2",
                parent_id: "prod-2",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
                title: "Lymphatic Drainage",
                is_active: true,
                created_at: "2025-01-02T11:00:00Z",
            }
        ]
    },
    {
        id: "prod-3",
        name: "Massage Sportif",
        description: "Massage profond ciblant les muscles tendus. Idéal pour les sportifs et personnes actives souhaitant améliorer leurs performances.",
        category: "cat-1",
        duration: 90,
        status: "published" as const,
        availability: "in-person" as const,
        bufferTime: 15,
        cancellationHours: 48,
        stripeProductId: "prod_stripe_3",
        metadata: { intensity: "high", targetAudience: "athletes" },
        createdAt: "2025-01-03T09:30:00Z",
        updatedAt: "2025-01-17T16:45:00Z",
        images: [
            {
                id: "img-prod-3",
                parent_id: "prod-3",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&auto=format&fit=crop",
                title: "Massage Sportif",
                is_active: true,
                created_at: "2025-01-03T09:30:00Z",
            }
        ]
    },
    {
        id: "prod-4",
        name: "Executive Performance Coaching",
        description: "One-on-one coaching for high-performers looking to optimize decision making and leadership presence.",
        category: "cat-2",
        duration: 60,
        status: "published" as const,
        availability: "online" as const,
        bufferTime: 5,
        cancellationHours: 48,
        stripeProductId: "prod_stripe_4",
        metadata: { sessionFormat: "1-on-1", focus: ["leadership", "decision-making"] },
        createdAt: "2025-01-04T14:00:00Z",
        updatedAt: "2025-01-18T11:20:00Z",
        images: [
            {
                id: "img-prod-4",
                parent_id: "prod-4",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop",
                title: "Executive Performance Coaching",
                is_active: true,
                created_at: "2025-01-04T14:00:00Z",
            }
        ]
    },
    {
        id: "prod-5",
        name: "Strength Foundations",
        description: "Improve range of motion and joint health through functional movement patterns. Build a solid foundation for long-term fitness.",
        category: "cat-3",
        duration: 90,
        status: "published" as const,
        availability: "hybrid" as const,
        bufferTime: 15,
        cancellationHours: 24,
        stripeProductId: "prod_stripe_5",
        metadata: { skillLevel: "beginner-intermediate", equipment: ["bodyweight", "resistance-bands"] },
        createdAt: "2025-01-05T10:15:00Z",
        updatedAt: "2025-01-19T13:00:00Z",
        images: [
            {
                id: "img-prod-5",
                parent_id: "prod-5",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&auto=format&fit=crop",
                title: "Strength Foundations",
                is_active: true,
                created_at: "2025-01-05T10:15:00Z",
            }
        ]
    },
    {
        id: "prod-6",
        name: "Aromathérapie",
        description: "Massage utilisant des huiles essentielles pour un bien-être physique et mental optimal. Personnalisé selon vos besoins.",
        category: "cat-4",
        duration: 75,
        status: "draft" as const,
        availability: "in-person" as const,
        bufferTime: 10,
        cancellationHours: 24,
        stripeProductId: "",
        metadata: { essentialOils: true, customizable: true },
        createdAt: "2025-01-06T15:30:00Z",
        updatedAt: "2025-01-20T10:00:00Z",
        images: [
            {
                id: "img-prod-6",
                parent_id: "prod-6",
                parent_type: "product",
                url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&auto=format&fit=crop",
                title: "Aromathérapie",
                is_active: true,
                created_at: "2025-01-06T15:30:00Z",
            }
        ]
    },
];

export const mockPrices = [
    {
        id: "price-1",
        productId: "prod-1",
        stripePriceId: "price_1ABC123XYZ",
        amount: 8000, // 80.00 in cents
        currency: "eur",
        interval: "one_time" as const,
        isActive: true,
        createdAt: "2025-01-01T10:00:00Z",
        updatedAt: "2025-01-15T14:30:00Z",
    },
    {
        id: "price-2",
        productId: "prod-2",
        stripePriceId: "price_2DEF456UVW",
        amount: 7500, // 75.00
        currency: "eur",
        interval: "one_time" as const,
        isActive: true,
        createdAt: "2025-01-02T11:00:00Z",
        updatedAt: "2025-01-16T09:00:00Z",
    },
    {
        id: "price-3",
        productId: "prod-3",
        stripePriceId: "price_3GHI789RST",
        amount: 12000, // 120.00
        currency: "eur",
        interval: "one_time" as const,
        isActive: true,
        createdAt: "2025-01-03T09:30:00Z",
        updatedAt: "2025-01-17T16:45:00Z",
    },
    {
        id: "price-4",
        productId: "prod-4",
        stripePriceId: "price_4JKL012OPQ",
        amount: 15000, // 150.00
        currency: "eur",
        interval: "one_time" as const,
        isActive: true,
        createdAt: "2025-01-04T14:00:00Z",
        updatedAt: "2025-01-18T11:20:00Z",
    },
    {
        id: "price-5",
        productId: "prod-4",
        stripePriceId: "price_5MNO345LMN",
        amount: 50000, // 500.00
        currency: "eur",
        interval: "month" as const,
        isActive: true,
        createdAt: "2025-01-04T14:30:00Z",
        updatedAt: "2025-01-18T11:30:00Z",
    },
    {
        id: "price-6",
        productId: "prod-5",
        stripePriceId: "price_6PQR678IJK",
        amount: 9500, // 95.00
        currency: "eur",
        interval: "one_time" as const,
        isActive: true,
        createdAt: "2025-01-05T10:15:00Z",
        updatedAt: "2025-01-19T13:00:00Z",
    },
    {
        id: "price-7",
        productId: "prod-5",
        stripePriceId: "price_7STU901GHI",
        amount: 30000, // 300.00
        currency: "eur",
        interval: "month" as const,
        isActive: false,
        createdAt: "2025-01-05T10:30:00Z",
        updatedAt: "2025-01-19T13:15:00Z",
    },
    {
        id: "price-8",
        productId: "prod-1",
        stripePriceId: "price_8VWX234DEF",
        amount: 80000, // 800.00
        currency: "eur",
        interval: "year" as const,
        isActive: false,
        createdAt: "2025-01-01T11:00:00Z",
        updatedAt: "2025-01-15T15:00:00Z",
    },
];

export const mockCoupons = [
    {
        id: "coupon-1",
        stripeCouponId: "coup_WELCOME2025",
        name: "Bienvenue 2025",
        percentOff: 25,
        duration: "once" as const,
        maxRedemptions: 100,
        timesRedeemed: 42,
        isValid: true,
        redeemBy: "2025-12-31T23:59:59Z",
        createdAt: "2025-01-01T10:00:00Z",
        updatedAt: "2025-01-15T14:30:00Z",
        metadata: { campaign: "new_year_2025" },
    },
    {
        id: "coupon-2",
        stripeCouponId: "coup_SUMMER50",
        name: "Été 50%",
        percentOff: 50,
        duration: "repeating" as const,
        durationInMonths: 3,
        maxRedemptions: 50,
        timesRedeemed: 8,
        isValid: true,
        redeemBy: "2025-09-30T23:59:59Z",
        createdAt: "2025-01-02T11:00:00Z",
        updatedAt: "2025-01-16T09:00:00Z",
        metadata: { seasonal: "summer" },
    },
    {
        id: "coupon-3",
        stripeCouponId: "coup_FIXED10EUR",
        name: "10€ de réduction",
        amountOff: 1000, // 10.00 EUR in cents
        currency: "eur",
        duration: "once" as const,
        maxRedemptions: 200,
        timesRedeemed: 156,
        isValid: true,
        createdAt: "2025-01-03T09:30:00Z",
        updatedAt: "2025-01-17T16:45:00Z",
        metadata: { type: "fixed_amount" },
    },
    {
        id: "coupon-4",
        stripeCouponId: "coup_VIPFOREVER",
        name: "VIP À Vie",
        percentOff: 15,
        duration: "forever" as const,
        timesRedeemed: 5,
        isValid: true,
        createdAt: "2025-01-04T14:00:00Z",
        updatedAt: "2025-01-18T11:20:00Z",
        metadata: { tier: "vip" },
    },
    {
        id: "coupon-5",
        stripeCouponId: "coup_EXPIRED2024",
        name: "Promo Été 2024",
        percentOff: 30,
        duration: "once" as const,
        maxRedemptions: 1000,
        timesRedeemed: 987,
        isValid: false,
        redeemBy: "2024-08-31T23:59:59Z",
        createdAt: "2024-06-01T10:00:00Z",
        updatedAt: "2024-09-01T00:00:00Z",
        metadata: { seasonal: "summer_2024" },
    },
    {
        id: "coupon-6",
        stripeCouponId: "coup_MONTHLY20",
        name: "Abonnement -20%",
        percentOff: 20,
        duration: "repeating" as const,
        durationInMonths: 12,
        maxRedemptions: 25,
        timesRedeemed: 25,
        isValid: false,
        createdAt: "2025-01-05T10:15:00Z",
        updatedAt: "2025-01-19T13:00:00Z",
        metadata: { subscription: "annual" },
    },
    {
        id: "coupon-7",
        stripeCouponId: "coup_FLASH15",
        name: "Flash Sale 15€",
        amountOff: 1500, // 15.00 EUR in cents
        currency: "eur",
        duration: "once" as const,
        maxRedemptions: 75,
        timesRedeemed: 3,
        isValid: true,
        redeemBy: "2025-02-28T23:59:59Z",
        createdAt: "2025-01-06T15:30:00Z",
        updatedAt: "2025-01-20T10:00:00Z",
        metadata: { promotion: "flash_sale" },
    },
    {
        id: "coupon-8",
        stripeCouponId: "coup_FIRST10",
        name: "Première séance",
        percentOff: 10,
        duration: "once" as const,
        timesRedeemed: 134,
        isValid: true,
        createdAt: "2025-01-07T11:00:00Z",
        updatedAt: "2025-01-21T09:30:00Z",
        metadata: { target: "new_customers" },
    },
];

export const mockPromotionCodes = [
    {
        id: "promo-1",
        stripePromotionId: "promo_WELCOME2025",
        couponId: "coupon-1",
        code: "BIENVENUE2025",
        active: true,
        maxRedemptions: 100,
        timesRedeemed: 42,
        expiresAt: "2025-12-31T23:59:59Z",
        firstTimeTransaction: false,
        createdAt: "2025-01-01T10:00:00Z",
        updatedAt: "2025-01-15T14:30:00Z",
        metadata: { campaign: "new_year_2025" },
    },
    {
        id: "promo-2",
        stripePromotionId: "promo_SUMMER50",
        couponId: "coupon-2",
        code: "ETE50",
        active: true,
        maxRedemptions: 50,
        timesRedeemed: 8,
        expiresAt: "2025-09-30T23:59:59Z",
        firstTimeTransaction: true,
        minimumAmount: 5000, // 50.00 EUR in cents
        minimumAmountCurrency: "eur",
        createdAt: "2025-01-02T11:00:00Z",
        updatedAt: "2025-01-16T09:00:00Z",
        metadata: { seasonal: "summer" },
    },
    {
        id: "promo-3",
        stripePromotionId: "promo_FIXED10",
        couponId: "coupon-3",
        code: "FIXE10EURO",
        active: true,
        maxRedemptions: 200,
        timesRedeemed: 156,
        firstTimeTransaction: false,
        createdAt: "2025-01-03T09:30:00Z",
        updatedAt: "2025-01-17T16:45:00Z",
        metadata: { type: "fixed_amount" },
    },
    {
        id: "promo-4",
        stripePromotionId: "promo_VIP",
        couponId: "coupon-4",
        code: "VIPCLIENT",
        active: true,
        timesRedeemed: 5,
        firstTimeTransaction: false,
        minimumAmount: 10000, // 100.00 EUR
        minimumAmountCurrency: "eur",
        createdAt: "2025-01-04T14:00:00Z",
        updatedAt: "2025-01-18T11:20:00Z",
        metadata: { tier: "vip" },
    },
    {
        id: "promo-5",
        stripePromotionId: "promo_EXPIRED",
        couponId: "coupon-5",
        code: "SUMMER2024",
        active: false,
        maxRedemptions: 1000,
        timesRedeemed: 987,
        expiresAt: "2024-08-31T23:59:59Z",
        firstTimeTransaction: false,
        createdAt: "2024-06-01T10:00:00Z",
        updatedAt: "2024-09-01T00:00:00Z",
        metadata: { seasonal: "summer_2024" },
    },
    {
        id: "promo-6",
        stripePromotionId: "promo_SUB20",
        couponId: "coupon-6",
        code: "ABO20MENSUEL",
        active: false,
        maxRedemptions: 25,
        timesRedeemed: 25,
        firstTimeTransaction: true,
        minimumAmount: 30000, // 300.00 EUR
        minimumAmountCurrency: "eur",
        createdAt: "2025-01-05T10:15:00Z",
        updatedAt: "2025-01-19T13:00:00Z",
        metadata: { subscription: "annual" },
    },
    {
        id: "promo-7",
        stripePromotionId: "promo_FLASH",
        couponId: "coupon-7",
        code: "FLASH15",
        active: true,
        maxRedemptions: 75,
        timesRedeemed: 3,
        expiresAt: "2025-02-28T23:59:59Z",
        firstTimeTransaction: false,
        minimumAmount: 8000, // 80.00 EUR
        minimumAmountCurrency: "eur",
        createdAt: "2025-01-06T15:30:00Z",
        updatedAt: "2025-01-20T10:00:00Z",
        metadata: { promotion: "flash_sale" },
    },
    {
        id: "promo-8",
        stripePromotionId: "promo_FIRST",
        couponId: "coupon-8",
        code: "PREMIERE",
        active: true,
        timesRedeemed: 134,
        firstTimeTransaction: true,
        createdAt: "2025-01-07T11:00:00Z",
        updatedAt: "2025-01-21T09:30:00Z",
        metadata: { target: "new_customers" },
    },
];
